### ISSUE TITLE
Read the I3C specification

### ISSUE THREAD

**Issue by muneebullashariff** [mbits-mirafra/i3c_avip#5]
- Here is the specification link just follow through with that.

[mipi_I3C-Basic_specification_v1-0.pdf](https://github.com/mbits-mirafra/i3c_avip/files/13345818/mipi_I3C-Basic_specification_v1-0.pdf)

**Comment by mahadevaswamy05** [comment]
**Some information about the I3C Protocol**

-**I3C**
- This bus is an evolutionary specification Improved inter-integrated circuit that builds upon the legacy of the I2C standard the aim is to reduce the number of physical pins used in the sensor system integrated.
- And support low power.
- High-speed digital communication typically associated with the I2C and SPI Interface.

**Comment by Gopalsuthar2308** [comment]
**There are many differences between the I3C and I2C However, some very unique features are as follows** 
1. It supports single data rate and high data rate mode.
2. I3C master supports the dynamic addressing to all the slaves present on the bus.
3. It supports an in-band Interrupt feature on the bus, So separate pins are not required.
4. It supports Hot join operation, In which slaves will send hot join requests to the master.
5. It is also power efficient and high speed compared to i2c.
6. Multi-master and Multi-slave capabilities, Single master and Single slave, Single master and Multi slave, multi-master and Single slave.

**Comment by mahadevaswamy05** [comment]
**Why I2C replace with the I3C**

While I2C has seen wide adoption over the years, it lacks some critical features – especially as mobile and mobile-influenced systems continue to integrate more and more sensors and other components. I2C limitations worth mentioning include 

- The 7-bit fixed address (no virtual addressing)
- No in-band interrupt (requires additional wires/pins)
- Limited data rate, and the ability of Targets to stretch the clock (thus potentially hanging up the system, etc.).
 
I3C aims both to fix these limitations and to add other enhancements.

**Comment by mahadevaswamy05** [comment]
## Bus Conditions

This Specification defines Open Drain Pull-Up and High-Keeper, as well as three distinct conditions in which the I3C Bus shall be considered inactive: **Bus Free**, **Bus Available**, and **Bus Idle** 

**Bus Free**: The Bus Free Condition is defined as a period occurring after a STOP and before a START, and with the following duration • For Pure Bus • For Mixed Bus.

**Bus Available Condition**:
The Bus Available Condition is defined as a period during which the Bus Free Condition is sustained continuously for a duration of at least 1us.

**Bus Idle Condition**
The I3C Bus Idle Condition is defined in order to help ensure Bus stability during Hot-Join events. The Bus Idle Condition is defined as a period during which the Bus Available Condition is sustained continuously for a duration of at least 200 microseconds.

**Comment by muneebullashariff** [comment]
Top 5 features to implement, which are unique for I3C
1. Write, start -> stop -> start -> stop. 
2. Read, start -> stop -> start -> stop. 
3. Arbitration
4. ACK and NACK
5. CCC commands - contain an 8-bit CCC ID describing the command that is executed. The MSB of this ID specifies whether this is a broadcast command (bit7 = 0) or a unicast one (bit7 = 1).
6. Clk stretching

**Comment by mahadevaswamy05** [comment]
## Acknowledge ACK and ACK

- The I2C protocol requires that the receiver acknowledges every byte sent.
- The acknowledge bit is a single bit that uses **0 for ACK and 1 for NACK** . 
- The ACK bit allows the Slave to communicate to the Master that the byte was successfully received and another byte may be sent. 
- The I2C specification defines the Acknowledge sequence as a logic low state of the SDA line during the 9th SCL pulse for any successfully transferred byte. 
- In the below picture the byte data is sent and at the 9th clock period, it gives the **ACK bit is 0**, which means a byte of data/Address was successfully received.   

![image](https://github.com/mbits-mirafra/i3c_avip/assets/106074838/626776fa-a349-4584-9f73-cda80ac46f83)
----
- In the below picture the byte data is sent and at the 9th clock period, it gives the **NACK bit is 1**, which means a byte of data/address was not received, In several conditions, and the condition is below.

i. The Slave was unable to receive/transmit Because it was performing some real-time function. and it's not ready to start communicating with the master.    
ii. During the transfer, the receiver gets data or commands that does not understand.
iii. During the transfer, the receiver cannot receive any more data bytes.
iv. The master is done reading the data and indicating this to the slave through the NACK. 
v. No receiver is present on the bus with the transmitted address so there is no device to respond with an acknowledge
 

![image](https://github.com/mbits-mirafra/i3c_avip/assets/106074838/91a14a16-b909-46a3-9b42-1d2e4c981964)

**Comment by muneebullashariff** [comment]
Top 5 features to implement, which are unique for I3C

1. Dynamic address
2. SDR -> CCC commands - contain an 8-bit CCC ID describing the command that is executed. The MSB of this ID specifies whether this is a broadcast command (bit7 = 0) or a unicast one (bit7 = 1).
3. Repeated Start
4. Multiple Masters and Multiple Slaves - But in the code, they wrote one master and one slave.
5. HDR
6. Heart join requet

**Comment by mahadevaswamy05** [comment]
## Hot join request 🟠

- The i3c bus protocol supports a mechanism for targets to join the i3c bus after the bus has already been configured this mechanism is called hot join.
-   **The Hot-Join feature** in I3C allows a Master to assign a dynamic address to Another slave when the slave requests it. 
- The hot-join mechanism is used when a target is mounted on the same **I3C** bus and remains depowered until needed. The target can then send a Hot-Join Request when it is powered up.
- The target must wait for the **bus idle condition** before sending the hot join request.
- The bus idle condition is defined as a period during which the bus available status is maintained for a duration of at least t idle that is 200 micros seconds. meaning that the SCL and SDA lines are both held high for the t idle.
- Once the joining target has been assigned its new dynamic address is fully operational on the i3c bus.
- Just follow the thought below picture for more clarity. 

i. The below picture shows already a master and slave have started communicating with each other.

![image](https://github.com/mbits-mirafra/i3c_avip/assets/106074838/cd5dc6b9-c6bf-4c38-a4eb-a79c7c5de613)

ii. In the below picture another slave wants to communicate with the master using the Hot join feature.
![image](https://github.com/mbits-mirafra/i3c_avip/assets/106074838/1b233063-bec9-4719-a8e8-d2117dd54d0f)

iii. This happened on the idle condition of the i3c protocol.
![image](https://github.com/mbits-mirafra/i3c_avip/assets/106074838/638f36ef-c6c6-4b56-bf01-8e9eb1e433df)

iv. Now Master sends the dynamic address to the slave and it starts communicating with the master.
![image](https://github.com/mbits-mirafra/i3c_avip/assets/106074838/280ec4fa-e7ab-4764-8219-936896117966)
